### PR TITLE
 Dropdown to display the no of questions one wish to have

### PR DESCRIPTION
**Pull request by nithindante**
Kindly check .

### CODE REVIEW

**Comment by benbenben147147147** [comment]
mostly correct. have a look at the individual options again. 🕺

**Comment by nithindante** [comment]
ooh my bad,  I am sorry, did you mean the dropdown list,  like right now, I just populated it with numbers, 1..10, should I change it ?

**Comment by benbenben147147147** [comment]
no, but the "values" are off, no?

**Comment by nithindante** [comment]
ooh my bad, I have done the required changes, can you just check ?

**Comment by benbenben147147147** [comment]
Its corect now. One more thing. Move your implementation into the settings.html file, because we want to adjust the number of questions not in the index.html, but in the settings.html. (This will by the way also fix the issue that you dont see your question selection -> see index.js the lines where you clear the container.innerHTML property)

**Comment by benbenben147147147** [comment]
looks good now, i merge it

**Pull request merged**
